# Use an official Python runtime as a parent image
FROM public.ecr.aws/lambda/python:3.9

# Set the working directory in the container to /app
WORKDIR /app

ADD requirements_simple.txt /app
RUN pip install -r requirements_simple.txt

# Add the current directory contents into the container at /app
ADD ./football_pipeline/s3_utils.py /app/football_pipeline/s3_utils.py
ADD ./football_pipeline/common.py /app/football_pipeline/common.py

ADD ./football_pipeline/expected_goals/fb_ref.py ${LAMBDA_TASK_ROOT}
ADD ./football_pipeline/match_results/football_data_co_uk.py ${LAMBDA_TASK_ROOT}

ENV PYTHONPATH "${PYTHONPATH}:/app"
#ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}"
#ENTRYPOINT ["python", "-c", "import football_data_co_uk; football_data_co_uk.clean_footballdata_handler({},{})"]
