version: 2

models:
  - name: fct_match_results_and_odds
    description: 'Check that matches are unique'

    tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - date
              - hometeam
              - awayteam
        - dbt_utils.expression_is_true:
            expression: "b365h > 0"

  - name: dim_match_expected_goals
    description: 'Check that xg matches are unique'

    tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - date
              - home
              - away

  - name: obt_match_results_all_details
    description: 'Match level results with all odds, XG, managers and lineups info.'
    tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - date
              - hometeam
              - awayteam

        - column_equality:
            column1: fthg
            column2: home_goals
        - column_equality:
            column1: ftag
            column2: away_goals