# map of team names from fbref to football_pipeline-data.co.uk (match_statistics table)
#TODO: consider converting to a 'link' table in s3/athena

FB_REF_FOOTBALL_DATA_TEAM_MAP = {
   'AFC Wimbledon': 'AFC Wimbledon',
   "Acc'ton Stanley": 'Accrington',
   'Arsenal': 'Arsenal',
   'Aston Villa': 'Aston Villa',
   'Barnsley': 'Barnsley',
   'Birmingham City': 'Birmingham',
   'Blackburn': 'Blackburn',
   'Blackpool': 'Blackpool',
   'Bolton': 'Bolton',
   'Bournemouth': 'Bournemouth',
   'Bradford City': 'Bradford',
   'Brentford': 'Brentford',
   'Brighton': 'Brighton',
   'Bristol City': 'Bristol City',
   'Bristol Rovers': 'Bristol Rvs',
   'Burnley': 'Burnley',
   'Burton Albion': 'Burton',
   'Bury': 'Bury',
   'Cambridge Utd': 'Cambridge',
   'Cardiff City': 'Cardiff',
   'Charlton Ath': 'Charlton',
   'Chelsea': 'Chelsea',
   'Cheltenham': 'Cheltenham',
   'Coventry City': 'Coventry',
   'Crewe Alexandra': 'Crewe',
   'Crystal Palace': 'Crystal Palace',
   'Derby County': 'Derby',
   'Doncaster': 'Doncaster',
   'Everton': 'Everton',
   'Fleetwood Town': 'Fleetwood Town',
   'Fulham': 'Fulham',
   'Gillingham': 'Gillingham',
   'Huddersfield': 'Huddersfield',
   'Hull City': 'Hull',
   'Ipswich Town': 'Ipswich',
   'Leeds United': 'Leeds',
   'Leicester City': 'Leicester',
   'Lincoln City': 'Lincoln',
   'Liverpool': 'Liverpool',
   'Luton Town': 'Luton',
   'MK Dons': 'Milton Keynes Dons',
   'Manchester City': 'Man City',
   'Manchester Utd':  'Man United',
   'Middlesbrough': 'Middlesbrough',
   'Millwall': 'Millwall' ,
   'Morecambe': 'Morecambe',
   'Newcastle Utd': 'Newcastle',
   'Northampton': 'Northampton',
   'Norwich City': 'Norwich',
   "Nott'ham Forest": "Nott'm Forest",
   'Oldham Athletic': 'Oldham',
   'Oxford United': 'Oxford',
   "P'borough Utd": 'Peterboro',
   'Plymouth Argyle': 'Plymouth',
   'Portsmouth': 'Portsmouth',
   'Preston': 'Preston',
   'QPR': 'QPR',
   'Reading': 'Reading',
   'Rochdale': 'Rochdale',
   'Rotherham Utd': 'Rotherham',
   'Scunthorpe Utd': 'Scunthorpe',
   'Sheffield Utd': 'Sheffield United',
   'Sheffield Weds': 'Sheffield Weds',
   'Shrewsbury': 'Shrewsbury',
   'Southampton': 'Southampton',
   'Southend United': 'Southend',
   'Stoke City': 'Stoke',
   'Sunderland': 'Sunderland',
   'Swansea City': 'Swansea',
   'Swindon Town': 'Swindon',
   'Tottenham': 'Tottenham',
   'Tranmere Rovers': 'Tranmere',
   'Walsall': 'Walsall',
   'Watford': 'Watford',
   'West Brom': 'West Brom',
   'West Ham': 'West Ham',
   'Wigan Athletic': 'Wigan',
   'Wolves': 'Wolves',
   'Wycombe': 'Wycombe'
}
